# Fly.io configuration for DDoS AI Detection System
# This file makes deployment super easy!

app = "ddos-ai-detection-system"
primary_region = "iad"

[build]

[env]
  DJANGO_SETTINGS_MODULE = "dl_ids.settings_production"
  PORT = "8000"
  PYTHON_VERSION = "3.9"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512

# Auto-deploy settings
[deploy]
  strategy = "immediate"
