# fly.toml app configuration file generated for ddos-ai-detection-system
app = "df-defence"
primary_region = "lhr"

[build]

[env]
  DJANGO_SETTINGS_MODULE = "dl_ids.settings_production"
  PORT = "8000"
  PYTHON_VERSION = "3.10"
  FLY_APP_NAME = "df-defence"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  grace_period = "30s"
  interval = "15s"
  method = "GET"
  timeout = "10s"
  path = "/health"
  protocol = "http"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512
