# Generated by Django 5.1.1 on 2025-03-11 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TuningModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tuning_id', models.UUIDField(unique=True)),
                ('tuning_model', models.CharField(max_length=64, verbose_name='调优模型')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('lr', models.FloatField(verbose_name='学习率')),
                ('wd', models.FloatField(verbose_name='权重衰减')),
                ('batch_size', models.IntegerField(verbose_name='批量大小')),
                ('num_epochs', models.IntegerField(verbose_name='训练轮数')),
                ('n_estimators', models.IntegerField(verbose_name='n_estimators')),
                ('max_depth', models.IntegerField(verbose_name='max_depth ')),
                ('accuracy', models.FloatField(blank=True, null=True, verbose_name='验证集准确率')),
                ('loss', models.FloatField(blank=True, null=True, verbose_name='损失值')),
                ('test_accuracy', models.FloatField(blank=True, null=True, verbose_name='测试集准确率')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tuning_model_user', to='main.user')),
            ],
            options={
                'db_table': 'tuning_models',
            },
        ),
    ]
