# Generated by Django 5.1.1 on 2025-08-02 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_tuningmodels'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src_ip', models.CharField(max_length=255, verbose_name='源IP地址')),
                ('dst_ip', models.CharField(max_length=255, verbose_name='目标IP地址')),
                ('src_port', models.CharField(max_length=255, verbose_name='源端口')),
                ('dst_port', models.CharField(max_length=255, verbose_name='目标端口')),
                ('protocol', models.CharField(max_length=255, verbose_name='协议')),
                ('features', models.TextField(verbose_name='特征内容')),
                ('create_time', models.DateTimeField(verbose_name='创建时间')),
                ('attack_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='攻击类型')),
                ('threat', models.CharField(blank=True, max_length=255, null=True, verbose_name='威胁级别')),
            ],
            options={
                'verbose_name': '流量日志',
                'verbose_name_plural': '流量日志',
                'db_table': 'tb_packetbaseinfo',
                'ordering': ['-create_time'],
            },
        ),
        migrations.RemoveField(
            model_name='tuningmodels',
            name='loss',
        ),
        migrations.RemoveField(
            model_name='tuningmodels',
            name='max_depth',
        ),
        migrations.RemoveField(
            model_name='tuningmodels',
            name='n_estimators',
        ),
        migrations.RemoveField(
            model_name='tuningmodels',
            name='test_accuracy',
        ),
        migrations.AddField(
            model_name='tuningmodels',
            name='f1',
            field=models.FloatField(blank=True, null=True, verbose_name='损失值'),
        ),
        migrations.AddField(
            model_name='tuningmodels',
            name='precision1',
            field=models.FloatField(null=True, verbose_name='precision1'),
        ),
        migrations.AddField(
            model_name='tuningmodels',
            name='recall',
            field=models.FloatField(blank=True, null=True, verbose_name='召回率'),
        ),
        migrations.AlterField(
            model_name='tuningmodels',
            name='accuracy',
            field=models.FloatField(null=True, verbose_name='准确率'),
        ),
    ]
